
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class formBuku extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rsCount, rs;
    DefaultTableModel tabel1;
    Object[] list_mhs = new Object[4]; //siapkan array yang akan dimasukkan ke table
    int x=0; //siapkan interger untuk nomor ascending
    dbConnection dbConn = new dbConnection();
    Connection con = dbConn.getConnection(); //mengoneksikan database ke form buku
    
    public formBuku() throws SQLException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        
        tabel1 =new DefaultTableModel();
        tabel.setModel(tabel1); //menulis di header
        tabel1.addColumn("No.");
        tabel1.addColumn("Nomor Rumah");
        tabel1.addColumn("Nama"); 
        tabel1.addColumn("Nomor");
        tabel1.addColumn("Villa Yang Ditempati");
        setResizable(false);  //tidak bisa diperbesar
        tampilkanDiTabel();
        //tidak bisa diklik
        update.setEnabled(false);

    }
    
    // class untuk menghapus semua data di form fill
    public void kosongkan(){
        inputNomorrmh.setText("");
        inputNama.setText("");
        inputNomor.setText("");
        inputVilla.setSelectedItem("");
    }
    
    // mngambil database
    public ArrayList[] getTlpList() throws SQLException{      
        String queryCount = "SELECT COUNT(*) as c FROM bukutelpon";
              
        st = con.createStatement();        
        rsCount = st.executeQuery(queryCount);
        int sizeTable=0;

        while(rsCount.next()){
            sizeTable = rsCount.getInt("c");
        }       
        ArrayList[] tlpList = new ArrayList[sizeTable];       
        String query = "SELECT * FROM bukutelpon";
           rs = st.executeQuery(query);

       int x=0;
        while(rs.next()){
            tlpList[x] = new ArrayList<>();
            tlpList[x].add(rs.getString("kode_rmh"));
            tlpList[x].add(rs.getString("nama"));
            tlpList[x].add(rs.getString("nmr_tlp"));
            tlpList[x].add(rs.getString("villa"));
            x++;
        }
        return tlpList;
    }
    
    // menampilkan database di form
    public void tampilkanDiTabel() throws SQLException{
        ArrayList[] list = getTlpList();
        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
       
        Object[] row = new Object[9];
        for(int i = 0; i<list.length; i++){
            row[0] = i+1;
            row[1] = list[i].get(0);
            row[2] = list[i].get(1);
            row[3] = list[i].get(2);
            row[4] = list[i].get(3);

            model.addRow(row);
        }       
    }
    
    // mengosongkan tabel database di form
    public void kosongkanTabel(){
        DefaultTableModel model = (DefaultTableModel)this.tabel.getModel();
        model.setRowCount(0);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNomorrmh = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        inputNomor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        inputVilla = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1385, 977));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 410, 183, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Nomer Telpon");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 460, 183, 25);

        inputNomorrmh.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inputNomorrmh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomorrmhActionPerformed(evt);
            }
        });
        getContentPane().add(inputNomorrmh);
        inputNomorrmh.setBounds(440, 360, 228, 31);

        inputNama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        getContentPane().add(inputNama);
        inputNama.setBounds(440, 410, 228, 31);

        inputNomor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(inputNomor);
        inputNomor.setBounds(440, 460, 228, 31);

        tabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(720, 330, 635, 620);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Villa Yang Ditempati");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 520, 183, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Nomor Rumah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 360, 183, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Simpan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 700, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Hapus");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 830, 50, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Update");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 700, 59, 20);

        simpan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-64.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(140, 630, 69, 65);

        hapus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-delete-bin-64.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(140, 750, 69, 65);

        update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-update-64 (1).png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(430, 630, 73, 65);

        keluar.setBackground(new java.awt.Color(204, 204, 255));
        keluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(50, 910, 85, 29);

        inputVilla.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inputVilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amatsuki", "Soraru", "USSS", "XYZ", "Eve", "Sou" }));
        getContentPane().add(inputVilla);
        inputVilla.setBounds(440, 520, 228, 34);

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-delete-40.png"))); // NOI18N
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(430, 760, 73, 57);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Cancel");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 830, 54, 20);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(720, 230, 260, 60);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(360, 230, 250, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UI Operasi Data Form Buku.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -30, 1390, 1030);

        setSize(new java.awt.Dimension(1385, 977));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if("".equals(inputNomorrmh.getText())||"".equals(inputNama.getText())||"".equals(inputNomor.getText())||"".equals(inputVilla.getSelectedItem()))
        {
            JOptionPane.showMessageDialog(this, "Data Invalid","Error",JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                st = con.createStatement();
                st.executeUpdate("INSERT INTO bukutelpon VALUES('" + inputNomorrmh.getText() + "','"
                    + inputNama.getText() + "','"
                    + inputNomor.getText() + "','"
                    + inputVilla.getSelectedItem() + "')");
                kosongkanTabel();
                kosongkan();
                tampilkanDiTabel();
                JOptionPane.showMessageDialog(null, "Kontak berhasil disimpan");
            } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Kontak tidak berhasil disimpan");
          }
        }
        
        
       

    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            con.createStatement().executeUpdate("UPDATE bukutelpon SET kode_rmh ='"+inputNomorrmh.getText()+"',nama ='"+inputNama.getText()+"',nmr_tlp ='"+inputNomor.getText()+"',villa ='"+inputVilla.getSelectedItem()+"' WHERE kode_rmh ='"+inputNomorrmh.getText()+"'");
            kosongkanTabel();
            kosongkan();
            tampilkanDiTabel();
            simpan.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Kontak berhasil diupdate");
        } catch (SQLException ex) {
            Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Kontak tidak berhasil diupdate");
            simpan.setEnabled(true);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            PreparedStatement ps = con.prepareStatement("DELETE FROM bukutelpon WHERE kode_rmh = ?");
            String nomorNya = inputNomorrmh.getText();
            ps.setString(1, nomorNya);
            ps.executeUpdate();
            simpan.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Kontak berhasil dihapus");
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Kontak tidak berhasil dihapus");
            simpan.setEnabled(true);
         }finally{
            try {
                kosongkan();
                kosongkanTabel();
                tampilkanDiTabel();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void inputNomorrmhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomorrmhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomorrmhActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        simpan.setEnabled(true);
        hapus.setEnabled(false);
        update.setEnabled(false);
        cancel.setEnabled(true);
        kosongkan();
    }//GEN-LAST:event_cancelActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        inputNomorrmh.setEditable(false);
        inputNomorrmh.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
        inputNama.setText(tabel.getValueAt(tabel.getSelectedRow(), 2).toString());
        inputNomor.setText(tabel.getValueAt(tabel.getSelectedRow(), 3).toString());
        inputVilla.setSelectedItem(tabel.getValueAt(tabel.getSelectedRow(), 4).toString());
        simpan.setEnabled(false);
        update.setEnabled(true);
        hapus.setEnabled(true);
    }//GEN-LAST:event_tabelMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setVisible(false);
        try {
            new tabelBuku().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formBuku().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNomor;
    private javax.swing.JTextField inputNomorrmh;
    private javax.swing.JComboBox<String> inputVilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
