
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class tabelBuku extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rsCount, rs;
    DefaultTableModel tabel1;
    Object[] list_mhs = new Object[4]; //siapkan array yang akan dimasukkan ke table
    int x=0; //siapkan interger untuk nomor ascending
    dbConnection dbConn = new dbConnection();
    Connection con = dbConn.getConnection(); //mengoneksikan database ke form buku
    
    public tabelBuku() throws SQLException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        
        tabel1 =new DefaultTableModel();
        tabel.setModel(tabel1); //menulis di header
        tabel1.addColumn("No.");
        tabel1.addColumn("Nomor Rumah");
        tabel1.addColumn("Nama"); 
        tabel1.addColumn("Nomor");
        tabel1.addColumn("Villa Yang Ditempati");
        setResizable(false);  //tidak bisa diperbesar
        tampilkanDiTabel();
        //tidak bisa diklik
        

    }
    
    // class untuk menghapus semua data di form fill
    
    // mngambil database
    public ArrayList[] getTlpList() throws SQLException{      
        String queryCount = "SELECT COUNT(*) as c FROM bukutelpon";
              
        st = con.createStatement();        
        rsCount = st.executeQuery(queryCount);
        int sizeTable=0;

        while(rsCount.next()){
            sizeTable = rsCount.getInt("c");
        }       
        ArrayList[] tlpList = new ArrayList[sizeTable];       
        String query = "SELECT * FROM bukutelpon";
           rs = st.executeQuery(query);

       int x=0;
        while(rs.next()){
            tlpList[x] = new ArrayList<>();
            tlpList[x].add(rs.getString("kode_rmh"));
            tlpList[x].add(rs.getString("nama"));
            tlpList[x].add(rs.getString("nmr_tlp"));
            tlpList[x].add(rs.getString("villa"));
            x++;
        }
        return tlpList;
    }
    
    // menampilkan database di form
    public void tampilkanDiTabel() throws SQLException{
        ArrayList[] list = getTlpList();
        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
       
        Object[] row = new Object[9];
        for(int i = 0; i<list.length; i++){
            row[0] = i+1;
            row[1] = list[i].get(0);
            row[2] = list[i].get(1);
            row[3] = list[i].get(2);
            row[4] = list[i].get(3);

            model.addRow(row);
        }       
    }
    
    // mengosongkan tabel database di form
    public void kosongkanTabel(){
        DefaultTableModel model = (DefaultTableModel)this.tabel.getModel();
        model.setRowCount(0);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1385, 977));
        getContentPane().setLayout(null);

        cetak.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-print-64.png"))); // NOI18N
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak);
        cetak.setBounds(1160, 480, 150, 100);

        tabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 320, 1040, 620);

        keluar.setBackground(new java.awt.Color(204, 204, 255));
        keluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(1190, 900, 85, 29);

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 230, 250, 60);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(730, 220, 260, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Print");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1210, 600, 51, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UI Data Tabel Form Buku.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -30, 1390, 1030);

        setSize(new java.awt.Dimension(1385, 977));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        JasperReport reports;

        String path=".\\src\\reportTelpon.jasper"; // mengambil file jasper report
        try {
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, con);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
            System.out.println("Masuk try");
        } catch (JRException ex) {
            Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        try {
            new formBuku().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(tabelBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formBuku().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formBuku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
